# ========== 太刀白刃 ==========
[[trigger]]
# 当有多个事件时，事件调用模式
# sequential_all: 顺序执行全部
# sequential_one: 顺序执行下一个
# random: 随机选取执行
action_mode = "sequential_all"

    # 触发条件设置（有且仅有一个）
    [trigger.trigger_on.longsword_level_changed]
    new = 1
    old = 0

    # 触发检查条件设置
    # 多个条件同时满足才会执行
    # [[trigger.check]]
    # weapon_type.value = 3

    # 触发事件设置
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_WHITE_DEFAULT><SIZE 25>太刀大人已解放至不屈白刃！</SIZE></STYL>"

# ========== 太刀黄刃 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.longsword_level_changed]
    new = 2
    old = 1

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_YELLOW_DEFAULT><SIZE 25>太刀大人已解放至永恒黄刃！</SIZE></STYL>"


# ========== 太刀红刃 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.longsword_level_changed]
    new = 3
    old = 2

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 25>太刀大人已解放至至尊红刃！</SIZE></STYL>"


# ========== 太刀进入任务 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.quest_state]
    value = 2

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>太刀侠加入狩猎！</SIZE></STYL>"


# ========== 太刀登龙动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 87 }

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>这登龙能空？！</SIZE></STYL>"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_BLUE_DEFAULT><SIZE 40>太刀侠魅力时刻，其他武器全体纳刀三分钟致敬！</SIZE></STYL>"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_YELLOW_DEFAULT><SIZE 40>呱！我要看这个！我就是要看这个吔！</SIZE></STYL>"


# ========== 太刀居合动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 102 }

    [[trigger.check]]
    weapon_type.value = 3

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>呱！强而有力！强而有力口牙！</SIZE></STYL>"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "你不知道我是<STYL MOJI_RED_DEFAULT><SIZE 40>玩太刀</SIZE></STYL>的？"


# ========== 虫棍进入任务 ==========
[[trigger]]
action_mode = "sequential_all"

    [trigger.trigger_on.quest_state]
    value = 2

    [[trigger.check]]
    weapon_type.value = 10

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>孩子别怕，我拿真黑龙棍来救你了！</SIZE></STYL>”"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_YELLOW_DEFAULT><SIZE 40>孩子别怕，我带着真·曼巴棍来救你了！</SIZE></STYL>"
     [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>真曼巴棍进入战斗，其他武器肘击后方可继续狩猎</SIZE></STYL>”"

    
# ========== 虫棍红灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    red = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>真黑龙棍已解放『至尊红盏』！！！</SIZE></STYL>"


# ========== 虫棍白灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    white = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_WHITE_DEFAULT><SIZE 40>真黑龙棍已解放『圣洁白盏』！！！</SIZE></STYL>"


# ========== 虫棍黄灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    yellow = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_ORANGE_DEFAULT><SIZE 40>真黑龙棍已解放『传奇橙盏』！！！</SIZE></STYL>"


# ========== 虫棍三灯 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.insect_glaive_light]
    red = { new = { gt = 0 } }
    white = { new = { gt = 0 } }
    yellow = { new = { gt = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>三灯封印解除！该轮到猎物们颤抖了！！！</SIZE></STYL>"
    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>真黑龙棍大人已开出至尊三灯，传说中的耐摔王出现了！！！</SIZE></STYL>"
     [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>真黑龙棍大人三灯齐聚，其他武器纳刀敬礼后方可继续！！！</SIZE></STYL>"


# ========== 猎虫强化动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 133 }

    [[trigger.check]]
    weapon_type.value = 10

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_BLUE_DEFAULT><SIZE 40>真黑龙棍大人发动了猎虫强化！</SIZE></STYL>"


### ========== 盾斧进入任务 ========== ###

    [trigger.trigger_on.quest_state]
    value = 2

    [[trigger.check]]
    weapon_type.value = 9

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_BLUE_DEFAULT><SIZE 40>真黑龙盾斧进入战斗，孩子们准备好迎接蓝火了吗？</SIZE></STYL>"



# ========== 盾斧瓶子充满 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    phials = { new = "full" }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>盾斧大人已装填至尊六瓶！！！</SIZE></STYL>"


# ========== 盾斧红剑动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 81 }

    [[trigger.check]]
    weapon_type.value = 9
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>盾斧大人已灌注炽烈锋刃！！！</SIZE></STYL>"


# ========== 盾斧超解动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 120 }

    [[trigger.check]]
    weapon_type.value = 9

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_YELLOW_DEFAULT><SIZE 40>盾斧大人已发动舍身重击！！！</SIZE></STYL>"



# ========== 盾斧大解动作 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.fsm]
    new = { target = 3, id = 118 }

    [[trigger.check]]
    weapon_type.value = 9

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_PURPLE_DEFAULT><SIZE 40>盾斧大人已发动沉重猛击！！！</SIZE></STYL>"


# ========== 盾斧电锯启用 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    power_axe_timer = { new = "enabled" }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>盾斧大人已启动爆裂魔锯，空中的小朋友们，要被肘击了哦</SIZE></STYL>"


# ========== 盾斧红盾启用 ==========
[[trigger]]
action_mode = "random"

    [trigger.trigger_on.charge_blade]
    shield_charge_timer = { new = { gt = 0 }, old = { le = 0 } }

    [[trigger.action]]
    cmd = "SendChatMessage"
    param = "<STYL MOJI_RED_DEFAULT><SIZE 40>盾斧大人已启动绝对铁壁！！！</SIZE></STYL>"

